name: Basic Python CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv and sync dependencies
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "backend/uv.lock"

    - name: Create virtual environment
      run: uv venv

    - name: Sync project
      run: uv sync --all-extras --dev

    - name: Lint with flake8
      run: |
        uv run flake8 src || true

    - name: Run tests
      run: |
        uv run pytest || truez
